version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5123:5432
    env_file:
      - db.env
    volumes:
      - ./pData:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    depends_on:
      - db